CREATE TABLE states (
	state_id SERIAL PRIMARY KEY,
	state_name VARCHAR(100) NOT NULL,
	state_abbr VARCHAR(10),
	country_id INT NOT NULL REFERENCES countries(country_id)
);
CREATE INDEX fts_state_name ON states USING GIN (to_tsvector('english', state_name));

INSERT INTO states (state_name, state_abbr, country_id)
VALUES
('Alabama', 'AL', 185),
('Alaska', 'AK', 185),
('Arizona', 'AZ', 185),
('Arkansas', 'AR', 185),
('California', 'CA', 185),
('Colorado', 'CO', 185),
('Connecticut', 'CT', 185),
('Delaware', 'DE', 185),
('District of Columbia', 'DC', 185),
('Florida', 'FL', 185),
('Georgia', 'GA', 185),
('Hawaii', 'HI', 185),
('Idaho', 'ID', 185),
('Illinois', 'IL', 185),
('Indiana', 'IN', 185),
('Iowa', 'IA', 185),
('Kansas', 'KS', 185),
('Kentucky', 'KY', 185),
('Louisiana', 'LA', 185),
('Maine', 'ME', 185),
('Montana', 'MT', 185),
('Nebraska', 'NE', 185),
('Nevada', 'NV', 185),
('New Hampshire', 'NH', 185),
('New Jersey', 'NJ', 185),
('New Mexico', 'NM', 185),
('New York', 'NY', 185),
('North Carolina', 'NC', 185),
('North Dakota', 'ND', 185),
('Ohio', 'OH', 185),
('Oklahoma', 'OK', 185),
('Oregon', 'OR', 185),
('Maryland', 'MD', 185),
('Massachusetts', 'MA', 185),
('Michigan', 'MI', 185),
('Minnesota', 'MN', 185),
('Mississippi', 'MS', 185),
('Missouri', 'MO', 185),
('Pennsylvania', 'PA', 185),
('Rhode Island', 'RI', 185),
('South Carolina', 'SC', 185),
('South Dakota', 'SD', 185),
('Tennessee', 'TN', 185),
('Texas', 'TX', 185),
('Utah', 'UT', 185),
('Vermont', 'VT', 185),
('Virginia', 'VA', 185),
('Washington', 'WA', 185),
('West Virginia', 'WV', 185),
('Wisconsin', 'WI', 185),
('Wyoming', 'WY', 185),
('American Samoa', 'AS', 185),
('Guam', 'GU', 185),
('Northern Mariana Islands', 'MP', 185),
('Puerto Rico', 'PR', 185),
('United States Minor Outlying Islands', 'UM', 185),
('Virgin Islands', 'VI', 185),
('Alberta', 'AB', 38),
('British Columbia', 'BC', 38),
('Manitoba', 'MB', 38),
('New Brunswick', 'NB', 38),
('Newfoundland and Labrador', 'NL', 38),
('Northwest Territories', 'NT', 38),
('Nova Scotia', 'NS', 38),
('Nunavut', 'NU', 38),
('Ontario', 'ON', 38),
('Prince Edward Island', 'PE', 38),
('Quebec', 'QC', 38),
('Saskatchewan', 'SK', 38),
('Yukon', 'YT', 38),
('Australian Capital Territory', 'ACT', 14),
('New South Wales', 'NSW', 14),
('Northern Territory', 'NT', 14),
('Queensland', 'QLD', 14),
('South Australia', 'SA', 14),
('Tasmania', 'TAS', 14),
('Victoria', 'VIC', 14),
('Western Australia', 'WA', 14),
('Baden-Württemberg', 'BW', 80),
('Bavaria', 'BY', 80),
('Berlin', 'BE', 80),
('Brandenburg', 'BB', 80),
('Bremen', 'HB', 80),
('Hamburg', 'HH', 80),
('Hesse', 'HE', 80),
('Lower Saxony', 'NI', 80),
('Mecklenburg-Vorpommern', 'MV', 80),
('North Rhine-Westphalia', 'NW', 80),
('Rhineland-Palatinate', 'RP', 80),
('Saarland', 'SL', 80),
('Saxony', 'SN', 80),
('Saxony-Anhalt', 'ST', 80),
('Schleswig-Holstein', 'SH', 80),
('Thuringia', 'TH', 80),
('Burgenland', '1', 14);
