CREATE TYPE education_level AS ENUM ('none', 'no_high_school', 'high_school', 'certificate', 'bootcamp', 'some_college', 'associates', 'bachelors', 'masters', 'doctorate', 'professional');
CREATE TABLE educational_qualifications (
	educational_qualification_id SERIAL PRIMARY KEY,
	job_posting_id INT NOT NULL REFERENCES job_postings(job_posting_id),
	education_level education_level NOT NULL,
	educational_field_id INT NOT NULL REFERENCES educational_fields(educational_field_id)
);

INSERT INTO educational_qualifications
(job_posting_id, education_level, educational_field_id)
VALUES
(1, 'bachelors', 1),
(1, 'bachelors', 2),
(1, 'bachelors', 3),
(1, 'bachelors', 4),
(1, 'bachelors', 5),
(1, 'bachelors', 6),
(1, 'bachelors', 7),
(1, 'bachelors', 8),
(1, 'bachelors', 9),
(1, 'bachelors', 10),
(2, 'bachelors', 1),
(2, 'bachelors', 2),
(2, 'bachelors', 3),
(2, 'bachelors', 4),
(2, 'bachelors', 5),
(2, 'bachelors', 6),
(2, 'bachelors', 7),
(2, 'bachelors', 8),
(2, 'bachelors', 9),
(2, 'bachelors', 10),
(3, 'bachelors', 1),
(3, 'bachelors', 2),
(3, 'bachelors', 3),
(3, 'bachelors', 4),
(3, 'bachelors', 5),
(3, 'bachelors', 6),
(3, 'bachelors', 7),
(3, 'bachelors', 8),
(3, 'bachelors', 9),
(3, 'bachelors', 10),
(4, 'bachelors', 1),
(4, 'bachelors', 2),
(4, 'bachelors', 3),
(4, 'bachelors', 4),
(4, 'bachelors', 5),
(4, 'bachelors', 6),
(4, 'bachelors', 7),
(4, 'bachelors', 8),
(4, 'bachelors', 9),
(4, 'bachelors', 10),
(5, 'bachelors', 1),
(5, 'bachelors', 2),
(5, 'bachelors', 3),
(5, 'bachelors', 4),
(5, 'bachelors', 5),
(5, 'bachelors', 6),
(5, 'bachelors', 7),
(5, 'bachelors', 8),
(5, 'bachelors', 9),
(5, 'bachelors', 10),
(6, 'bachelors', 1),
(6, 'bachelors', 2),
(6, 'bachelors', 3),
(6, 'bachelors', 4),
(6, 'bachelors', 5),
(6, 'bachelors', 6),
(6, 'bachelors', 7),
(6, 'bachelors', 8),
(6, 'bachelors', 9),
(6, 'bachelors', 10),
(7, 'bachelors', 1),
(7, 'bachelors', 2),
(7, 'bachelors', 3),
(7, 'bachelors', 4),
(7, 'bachelors', 5),
(7, 'bachelors', 6),
(7, 'bachelors', 7),
(7, 'bachelors', 8),
(7, 'bachelors', 9),
(7, 'bachelors', 10),
(8, 'bachelors', 1),
(8, 'bachelors', 2),
(8, 'bachelors', 3),
(8, 'bachelors', 4),
(8, 'bachelors', 5);
