CREATE TABLE cities ( 
	city_id SERIAL PRIMARY KEY,
	city_name VARCHAR(255) NOT NULL,
	state_id INT NOT NULL REFERENCES states(state_id)
);

INSERT INTO cities
(city_name, state_id)
VALUES
('New York', 1),
('Los Angeles', 2),
('Chicago', 3),
('Houston', 4),
('Phoenix', 5),
('Philadelphia', 6),
('San Antonio', 7),
('San Diego', 8),
('Dallas', 9),
('San Jose', 10),
('Austin', 11),
('Jacksonville', 12),
('Fort Worth', 13),
('Columbus', 14),
('San Francisco', 15),
('Charlotte', 16),
('Indianapolis', 17),
('Seattle', 18),
('Denver', 19),
('Washington', 20),
('Boston', 21),
('El Paso', 22),
('Detroit', 23),
('Nashville', 24),
('Portland', 25),
('Memphis', 26),
('Oklahoma City', 27),
('Las Vegas', 28),
('Louisville', 29),
('Baltimore', 30),
('Milwaukee', 31),
('Albuquerque', 32),
('Tucson', 33),
('Fresno', 34),
('Mesa', 35),
('Sacramento', 36),
('Atlanta', 37),
('Kansas City', 38),
('Colorado Springs', 39),
('Miami', 40),
('Raleigh', 41),
('Omaha', 42),
('Long Beach', 43),
('Virginia Beach', 44),
('Oakland', 45),
('Minneapolis', 46),
('Tulsa', 47),
('Arlington', 48),
('Tampa', 49),
('New Orleans', 50),
('Wichita', 51),
('Bakersfield', 52),
('Cleveland', 53),
('Aurora', 54),
('Anaheim', 55),
('Honolulu', 56),
('Santa Ana', 57),
('Riverside', 58),
('Corpus Christi', 59),
('Lexington', 60),
('Stockton', 61),
('Henderson', 62),
('Saint Paul', 63),
('St. Louis', 64),
('Cincinnati', 65),
('Pittsburgh', 66),
('Greensboro', 67),
('Anchorage', 68),
('Plano', 69),
('Lincoln', 70),
('Orlando', 71),
('Irvine', 72),
('Newark', 73),
('Toledo', 74),
('Durham', 75),
('Chula Vista', 76),
('Fort Wayne', 77),
('Jersey City', 78),
('St. Petersburg', 79),
('Laredo', 80),
('Madison', 81),
('Chandler', 82),
('Buffalo', 83),
('Lubbock', 84),
('Scottsdale', 85),
('Reno', 86),
('Glendale', 87),
('Gilbert', 88),
('Winston–Salem', 89);
