CREATE TYPE company_size AS ENUM ('startup', 'medium', 'large', 'enterprise');
CREATE TABLE companies (
	company_id SERIAL PRIMARY KEY,
	company_name VARCHAR(255) NOT NULL,
	industry_id INT REFERENCES industries(industry_id),
	company_logo TEXT,
	company_size company_size
);
CREATE INDEX fts_company_name ON companies USING GIN (to_tsvector('english', company_name));

INSERT INTO companies
(company_name, industry_id, company_logo, company_size)
VALUES
('Google', 1, 'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png', 'enterprise'),
('Facebook', 2, 'https://www.facebook.com/images/fb_icon_325x325.png', 'large'),
('Amazon', 3, 'https://www.amazon.com/favicon.ico', 'enterprise'),
('Microsoft', 1, 'https://www.microsoft.com/favicon.ico', 'enterprise'),
('Apple', 1, 'https://www.apple.com/favicon.ico', 'enterprise'),
('Netflix', 1, 'https://www.netflix.com/favicon.ico', 'large'),
('Twitter', 2, 'https://www.twitter.com/favicon.ico', 'medium'),
('LinkedIn', 2, 'https://www.linkedin.com/favicon.ico', 'large'),
('Uber', 3, 'https://www.uber.com/favicon.ico', 'large'),
('Airbnb', 3, 'https://www.airbnb.com/favicon.ico', 'large'),
('Lyft', 3, 'https://www.lyft.com/favicon.ico', 'medium'),
('DoorDash', 3, 'https://www.doordash.com/favicon.ico', 'medium'),
('Instacart', 3, 'https://www.instacart.com/favicon.ico', 'medium'),
('TikTok', 2, 'https://www.tiktok.com/favicon.ico', 'medium'),
('Snapchat', 2, 'https://www.snapchat.com/favicon.ico', 'medium'),
('Pinterest', 2, 'https://www.pinterest.com/favicon.ico', 'medium'),
('Twitch', 1, 'https://www.twitch.tv/favicon.ico', 'medium'),
('Reddit', 1, 'https://www.reddit.com/favicon.ico', 'medium'),
('Spotify', 1, 'https://www.spotify.com/favicon.ico', 'medium'),
('Slack', 1, 'https://www.slack.com/favicon.ico', 'medium'),
('Zoom', 1, 'https://www.zoom.us/favicon.ico', 'medium'),
('Etsy', 3, 'https://www.etsy.com/favicon.ico', 'medium'),
('Shopify', 3, 'https://www.shopify.com/favicon.ico', 'medium'),
('Salesforce', 1, 'https://www.salesforce.com/favicon.ico', 'enterprise'),
('Oracle', 1, 'https://www.oracle.com/favicon.ico', 'enterprise'),
('IBM', 1, 'https://www.ibm.com/favicon.ico', 'enterprise'),
('Intel', 1, 'https://www.intel.com/favicon.ico', 'enterprise'),
('HP', 1, 'https://www.hp.com/favicon.ico', 'enterprise'),
('Dell', 1, 'https://www.dell.com/favicon.ico', 'enterprise'),
('Cisco', 1, 'https://www.cisco.com/favicon.ico', 'enterprise'),
('Adobe', 1, 'https://www.adobe.com/favicon.ico', 'enterprise'),
('VMware', 1, 'https://www.vmware.com/favicon.ico', 'enterprise'),
('Nvidia', 1, 'https://www.nvidia.com/favicon.ico', 'enterprise'),
('Qualcomm', 1, 'https://www.qualcomm.com/favicon.ico', 'enterprise'),
('PayPal', 3, 'https://www.paypal.com/favicon.ico', 'enterprise'),
('Square', 3, 'https://www.squareup.com/favicon.ico', 'enterprise'),
('Stripe', 3, 'https://www.stripe.com/favicon.ico', 'enterprise'),
('Coinbase', 3, 'https://www.coinbase.com/favicon.ico', 'enterprise'),
('Robinhood', 3, 'https://www.robinhood.com/favicon.ico', 'enterprise'),
('Walmart', 3, 'https://www.walmart.com/favicon.ico', 'enterprise'),
('Target', 3, 'https://www.target.com/favicon.ico', 'enterprise'),
('Best Buy', 3, 'https://www.bestbuy.com/favicon.ico', 'enterprise'),
('Costco', 3, 'https://www.costco.com/favicon.ico', 'enterprise'),
('Home Depot', 3, 'https://www.homedepot.com/favicon.ico', 'enterprise'),
('Lowe''s', 3, 'https://www.lowes.com/favicon.ico', 'enterprise'),
('Starbucks', 3, 'https://www.starbucks.com/favicon.ico', 'enterprise'),
('McDonald''s', 3, 'https://www.mcdonalds.com/favicon.ico', 'enterprise'),
('Burger King', 3, 'https://www.bk.com/favicon.ico', 'enterprise'),
('Wendy''s', 3, 'https://www.wendys.com/favicon.ico', 'enterprise'),
('Chick-fil-A', 3, 'https://www.chick-fil-a.com/favicon.ico', 'enterprise'),
('Subway', 3, 'https://www.subway.com/favicon.ico', 'enterprise'),
('Chipotle', 3, 'https://www.chipotle.com/favicon.ico', 'enterprise'),
('Taco Bell', 3, 'https://www.tacobell.com/favicon.ico', 'enterprise');
