CREATE TABLE cities ( 
	city_id SERIAL PRIMARY KEY,
	city_name VARCHAR(255) NOT NULL,
	state_id INT NOT NULL REFERENCES states(state_id)
);

INSERT INTO cities
(city_name, state_id)
VALUES
('New York', 27),
('Denver', 6),
('Los Angeles', 5),
('San Francisco', 5),
('Chicago', 14),
('Houston', 40),
('Dallas', 40),
('Seattle', 47),
('Portland', 47),
('Miami', 9),
('Atlanta', 10),
('Boston', 21),
('Philadelphia', 38),
('Washington', 8),
('Phoenix', 3),
('San Diego', 5),
('Las Vegas', 3),
('San Antonio', 40),
('Austin', 40),
('Minneapolis', 23),
('St. Paul', 23),
('St. Louis', 32),
('Kansas City', 32),
('New Orleans', 18),
('Detroit', 22),
('Cleveland', 35),
('Columbus', 35),
('Cincinnati', 35),
('Indianapolis', 15),
('Nashville', 42),
('Memphis', 42),
('Baltimore', 8),
('Charlotte', 28),
('Raleigh', 28),
('Pittsburgh', 38),
('Milwaukee', 44),
('Tampa', 9),
('Orlando', 9),
('Jacksonville', 9),
('Salt Lake City', 45),
('San Jose', 5),
('Sacramento', 5),
('Oakland', 5),
('Honolulu', 12),
('Anchorage', 2),
('Boise', 13);
