CREATE TABLE educational_fields (
	educational_field_id SERIAL PRIMARY KEY,
	educational_field VARCHAR(255) NOT NULL
);
CREATE INDEX fts_educational_field ON educational_fields USING GIN (to_tsvector('english', educational_field));

INSERT INTO educational_fields
(educational_field)
VALUES
('Computer Science'),
('Computer Engineering'),
('Software Engineering'),
('Electrical Engineering'),
('Mechanical Engineering'),
('Civil Engineering'),
('Chemical Engineering'),
('Industrial Engineering'),
('Aerospace Engineering'),
('Biomedical Engineering'),
('Bioengineering'),
('Biotechnology'),
('Biology'),
('Chemistry'),
('Physics'),
('Mathematics'),
('Statistics'),
('Data Science'),
('Information Technology'),
('Information Systems'),
('Business'),
('Finance'),
('Accounting'),
('Economics'),
('Marketing'),
('Management'),
('Human Resources'),
('Communications'),
('Journalism'),
('English'),
('History'),
('Psychology'),
('Sociology'),
('Political Science'),
('Philosophy'),
('Art'),
('Music'),
('Film'),
('Theater'),
('Dance'),
('Architecture'),
('Urban Planning'),
('Public Health'),
('Nursing'),
('Medicine'),
('Pharmacy'),
('Dentistry'),
('Veterinary Medicine'),
('Law'),
('Education'),
('Other');
